[global]
# All input and output files are stored in this directory
workdir = WORKDIR_PLACEHOLDER/
# Name of the observatory
observatory = Keck Observatory
# Today's date
current_day = CURRENT_DATE_PLACEHOLDER
# Semester start date
semester_start_day = START_DATE_PLACEHOLDER
# Semester end date
semester_end_day = END_DATE_PLACEHOLDER
# Semester ID
semester = SEMESTER_PLACEHOLDER

[data]
# name of allocation file 
allocation_file = allocation.csv
# name of past history file 
past_file = past.csv
# name of request file 
request_file = request.csv
# name of custom file 
custom_file = custom.csv
# name of filler file
filler_file = fillers.csv

[semester]
# Size of one slot, in minutes
slot_size = 5
# Run a weather loss model in the autoscheduler
run_weather_loss = False
# Specify a random seed. In the paper for weather testing, we use 24 through 33
random_seed = 24
# Run the bonus round of scheduling
run_bonus_round = False
# Percent of request's n_inter_max the can be scheduled in bonus round
maximum_bonus_size = 0.5
# % gap between optimal and current solution to stop the solve
max_solve_gap = 0.05
# Maximum time that can be spent solving the model
max_solve_time = 300
# Show the Gurobi output in the terminal
show_gurobi_output = True

[night]
# % gap between optimal and current solution to stop the solve
max_solve_gap = 0.05
# Maximum time that can be spent solving the model
max_solve_time = 120
# Show the Gurobi output in the terminal
show_gurobi_output = True

[webapp]
# Date time format
date_time_format = %Y-%m-%dT%H:%M:%S.%f
# Bands
bands = band1, band3
# UpTree path
uptree_path = .
# Admin user IDs
admin = 4866

[kpf_cc] 
server = "", #vm-sumongo
collection = "astroq_results"
user = "",
pwd = ""
auth = "",
type = "mongodb"